### ISSUE TITLE
[Question] Profile Syncing

### ISSUE THREAD

**Issue by plambhsa** [aaronpowell/vscode-profile-switcher#1]
Is there a way to sync profiles between computers? I'd like to be able to specify the directory the profiles are saved in (like a Dropbox folder) or to do something like the Sync Settings extension does.

**Comment by mubaidr** [comment]
Yes, syncing profiles using `gist` between different setups would be awesome.

**Comment by aaronpowell** [comment]
Profile's will sync if you're using Settings Sync as all the information is stored in the `settings.json` file which Settings Sync looks at. No need to do anything special! 😁

**Comment by plambhsa** [comment]
Sounds great, thanks!
