### ISSUE TITLE
Profile switcher and settings sync not working together 

### ISSUE THREAD

**Issue by taigi100** [aaronpowell/vscode-profile-switcher#16]
Hey, recently had this issue with settings sync and realised it might be due to having the profile switcher extension. I'll link the issue here: [code-settings issue#1039](https://github.com/shanalikhan/code-settings-sync/issues/1039)

**Comment by jabacchetta** [comment]
I wonder if it has to do with the size of `settings.json` and `globalStorage` being uploaded to the gist.

**Comment by AlphaKennyBudy** [comment]
Is someone going to fix it? Really stuck with it.

**Comment by jdpipkin** [comment]
A work around for this is to update your `syncLocalSettings.json` file to include `        "aaronpowell.vscode-profile-switcher"` under `ignoreUploadFolders` 

I had to use a new gist, but it seems to be working now.

**Comment by AlphaKennyBudy** [comment]
Thank you! It worked for me, but I had to create new syncSettings Gist since mine uploaded a lot of files (even images etc), so now my Gist is full of garbage.

**Comment by aaronpowell** [comment]
Closing as VS Code has settings sync built in so I won't be maintaining any compatibility with the third-party one.
