### ISSUE TITLE
Error while saving or loading profile

### ISSUE THREAD

**Issue by mcollier** [aaronpowell/vscode-profile-switcher#3]
When attempting to save or load a profile, I receive an error bubble in VS Code.

![vscode profile switcher error bubble](https://user-images.githubusercontent.com/1142273/60461841-bd8ea800-9c15-11e9-9e8b-5cbd7e0b5aba.jpg)

**Comment by aaronpowell** [comment]
Are you able to provide me your `settings.json` file?

**Comment by mcollier** [comment]
@aaronpowell Yes. I've attached the settings file here (in the .zip).
[settings.zip](https://github.com/aaronpowell/vscode-profile-switcher/files/3350064/settings.zip)

**Comment by aaronpowell** [comment]
Ah, it's what I was expecting, there's a comment (which is on line 1) of the `settings.json` file. VS Code supports comments in that file, even though they aren't part of the JSON spec.

Currently I read `settings.json` as JSON, which explodes with the comment.

I'll put it on the backlog to fix (I'll find a npm package for it). In the mean time, if you remove your comment it should work.

**Comment by mcollier** [comment]
Yes, that seems to be the trick. It works with the comment removed.
