### ISSUE TITLE
Short-cut command to switch to a specific profile?

### ISSUE THREAD

**Issue by ianjukes** [aaronpowell/vscode-profile-switcher#34]
I would like to be able to bind a _specific_ profile to a _specific_ keyboard short-cut via the `extension.selectProfile` command. For example, I have one profile for Python development, one for Java8 and one for Java11. It would be fantastic to be able to hit a key combination to switch to these directly. This might be possible but I'm not sure how to do it if it is?

**Comment by aaronpowell** [comment]
Unfortunately not. Because profile names are dynamic, VS Code isn't aware of them until the list is requests by the `Switch Profile` command and it's not possible to dynamically register new commands (which is what you'd need to do, register a command of `Switch Profile <blah>`.
