### ISSUE TITLE
Trailing commas in `settings.json`

### ISSUE THREAD

**Issue by zingmane** [aaronpowell/vscode-profile-switcher#8]
Saving profile runs on error if the config has trailing commas any where in the `settings.json`.
The error message was also very shortened, so I had to look a while to find the issue.
Unfortunately the JSON specification does not allow a trailing commas, but code has no problem with it, so I think the profile switscher shouldn't either.

This is the snippet that caused the error.

`"files.exclude": {
   "**/.git": true,
 },
`

**Comment by aaronpowell** [comment]
Hmm, I use the same parser that Code itself uses to read the JSON in so I'm surprised that this results in an error.

**Comment by aaronpowell** [comment]
Fixed in release `0.3.1`
